<?php

namespace Voodoo\Doll\Auth;

/**
 * Test class for Session.
 * Generated by PHPUnit on 2014-02-13 at 04:59:02.
 */
class SessionTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Session
     */
    protected $object;


    protected function setUp() {
        $this->object = new Session;
    }


    protected function tearDown() {
        
    }

    public function testCall() {
        $session = @$this->object->createNew(1234);
        $this->assertEquals(1234, $session->user_id);
    }

}

?>
